Combined graveyard related bash scripts
svalinn/DAGMC-viz pull request #14
Opened 2018-10-04 20:03 UTC by piperlincoln

Updated GraveIdentifyAndRemove.py to include functionality from GraveIdentifier.sh, GraveRemove.sh, CurvesNoGrave.sh, and SurfacesNoGrave.sh. Wrote a new function to identify and return EntitySets of a user supplied Category Tag value. (Specified in #6).

2018-10-07 12:06 UTC, pshriwise requested changes
Any particular reason for the change from EntitySet to entity set? 

I don't have a particular preference for the purposes of this script. I'm just curious 😃 

Looks good overall! That function will come in handy elsewhere for sure.

2018-10-07 12:06 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
> +def get_sets_by_category(mb_core,category_name):
pep8 - space between arguments here

2018-10-07 12:06 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
> +           A PyMOAB core instance with a loaded data file.
Nice work being specific about the core needing a loaded file. It would be an easy thing to leave out.

2018-10-07 12:06 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
> +                                                                 tag_category, group_tag_values))
Indentation might be a little off here?

2018-10-07 12:06 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
> +    group_categories = get_sets_by_category(mb,"Group")
space between arguments here as well

2018-10-08 19:04 UTC, piperlincoln commented
@pshriwise I was experimenting to see which I preferred and I decided to use "EntitySet", "Category tag", and "Name tag" which are now consistent throughout the script! Also, I have made the PEP8 spacing updates that you requested!

2018-10-08 19:38 UTC, pshriwise commented
This looks good to me @piperlincoln! I'll wait until the end of the day to merge in case other reviewers have comments.

2018-10-30 21:25 UTC, merged