Raise exception if graveyard is not found
svalinn/DAGMC-viz pull request #23
Opened 2018-11-19 20:27 UTC by piperlincoln

Raise exception in `remove_graveyard` of `GraveIdentifyAndRemove.py` if no graveyard EntitySet is found. (Specified in #19).

2018-11-20 18:26 UTC, pshriwise requested changes
A quick comment on Exceptions

2018-11-20 18:26 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
> +        raise Exception()
I think we may want to use a more specific Exception. [Here](https://docs.python.org/3/library/exceptions.html) is a list of them. They all have different purposes and a cursory look at them makes me think that the `LookupError` might be the most appropriate, but there could be a better one in there for sure. 

(So you know I'm not being super picky...) This matters because is allows other exceptions related to type errors, file input/output, etc. to be raised an differentiated from the general `Exception` type. These can then still report information to the user about what is going wrong and/or stop the program if needed while we catch this specific error type, knowing what the failure mode is in this case.

2018-11-20 18:26 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
> +        raise Exception()
Also I think that you can pass a string to this exception which will describe why it was raised which is typically nice for users to know if the code does in fact fail :)

2018-11-28 15:38 UTC, pshriwise requested changes
A couple more small things and then this LGTM! Thanks @piperlincoln!

2018-11-28 15:38 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
> +       Exception: If no graveyard EntitySet is found.
We'll probably want to include the type of exception here. (Lookup was a good choice btw)

2018-11-28 15:38 UTC, pshriwise commented on PythonTool/GraveIdentifyAndRemove.py
>      print(graveyard_sets)
Do we always want to print this?

2018-11-28 22:25 UTC, piperlincoln commented on PythonTool/GraveIdentifyAndRemove.py
>      print(graveyard_sets)
I suppose not! I could include an option to with argparse and have the default be not printing anything!

2018-11-30 15:00 UTC, pshriwise commented
This looks good to me. Will merge at EOD

2018-11-30 16:08 UTC, pshriwise approved these changes

2018-11-30 23:10 UTC, pshriwise commented
Thanks @piperlincoln!

2018-11-30 23:10 UTC, merged